version: '3'
services:
  api-db-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dataops_papagali
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESLQ_DATABASE=dataops_papagali
    ports:
      - "3333:3333"
    volumes:
      - ./papagali_dataops:/src/
      - nodemodules:/src/node_modules

volumes:
    nodemodules: {}